language: bash
services: docker

before_script:
  - image55="melkorm/php-docker:5.5"
  - image56="melkorm/php-docker:5.6"
  - image70="melkorm/php-docker:7.0"

script:
  - docker build -q -t "$image56" ./5.5/
  - docker build -q -t "$image56" ./5.6/
  - docker build -q -t "$image70" ./7.0/

after_script:
  - docker images
